#include <soc/samsung/fvmap.h>

enum acpm_dvfs_id {
	MIF = ACPM_VCLK_TYPE,
	INT,
	CPUCL0,
	G3D,
	AUD,
	DISP,
	CP,
//	GNSS,
//	WLBT,
	DVS,
};

struct vclk acpm_vclk_list[] = {
	CMUCAL_ACPM_VCLK(MIF, NULL, NULL, NULL, NULL, MARGIN_MIF, 0),
	CMUCAL_ACPM_VCLK(INT, NULL, NULL, NULL, NULL, MARGIN_INT, 0),
	CMUCAL_ACPM_VCLK(CPUCL0, NULL, NULL, NULL, NULL, MARGIN_CPUCL0, 1),
	CMUCAL_ACPM_VCLK(G3D, NULL, NULL, NULL, NULL, MARGIN_G3D, 0),
	CMUCAL_ACPM_VCLK(AUD, NULL, NULL, NULL, NULL, MARGIN_AUD, 0),
	CMUCAL_ACPM_VCLK(DISP, NULL, NULL, NULL, NULL, MARGIN_DISP, 0),
	CMUCAL_ACPM_VCLK(CP, NULL, NULL, NULL, NULL, MARGIN_CP, 0),
//	CMUCAL_ACPM_VCLK(GNSS, NULL, NULL, NULL, NULL, MARGIN_GNSS, 0),
//	CMUCAL_ACPM_VCLK(WLBT, NULL, NULL, NULL, NULL, MARGIN_WLBT, 0),
};

unsigned int acpm_vclk_size = ARRAY_SIZE(acpm_vclk_list);

