snd-soc-aud9001-objs := aud9001x.o
snd-soc-aud9001-dump-objs := aud9001x-dump.o

obj-$(CONFIG_SND_SOC_SAMSUNG_CODEC)  += snd-soc-aud9001.o
obj-$(CONFIG_SND_SOC_SAMSUNG_CODEC)  += snd-soc-aud9001-dump.o
