# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the kernel battery drivers.
#

obj-$(CONFIG_SB_CORE)			+=	core/
obj-$(CONFIG_SB_CONTROL)		+=	control/
obj-$(CONFIG_SB_MODULE)			+=	module/

obj-$(CONFIG_BATTERY_SAMSUNG)	+=	fuelgauge/ charger/ wireless/ common/
