# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the kernel S2MPW03 fuelgauge driver.
#

# Object files in subdirectories

obj-$(CONFIG_FUELGAUGE_S2MPW03)					+= s2mpw03-fuelgauge.o
s2mpw03-fuelgauge-$(CONFIG_FUELGAUGE_S2MPW03)	+= s2mpw03_fuelgauge.o

subdir-ccflags-y := -Wformat
