# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the kernel battery util modules.
#

# Object files in subdirectories

obj-$(CONFIG_SB_ADC)		+=	adc/
obj-$(CONFIG_SB_CISD)		+=	cisd/
obj-$(CONFIG_SB_WORK)		+=	work/
obj-$(CONFIG_SB_STARTUP)	+=	startup/
