# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the kernel adc module.
#

# Object files in subdirectories

obj-$(CONFIG_SB_ADC)	+= sb-adc.o
sb-adc-$(CONFIG_SB_ADC)	+= sb_adc.o

subdir-ccflags-y := -Wformat
