#
# Copyright (c) 2012 Samsung Electronics Co., Ltd.
#		http://www.samsung.com
#
# Licensed under GPLv2
#

ccflags-y += -I$(srctree)/drivers/media/platform/exynos/scaler -Wformat

scaler-objs := scaler-core.o scaler-regs.o scaler-debug.o scaler-ext.o
obj-$(CONFIG_VIDEO_EXYNOS_SCALER)	+= scaler.o
