# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the kernel cisd module.
#

# Object files in subdirectories

obj-$(CONFIG_SB_CISD)		+= sb-cisd.o
sb-cisd-$(CONFIG_SB_CISD)	+= sb_cisd.o

subdir-ccflags-y := -Wformat
